# Generated by Django 2.2 on 2019-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soul',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cause', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
