# Generated by Django 2.2 on 2019-06-11 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='meal date')),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
                ('soul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Soul')),
            ],
        ),
        migrations.DeleteModel(
            name='Feeding',
        ),
    ]
