# Generated by Django 2.2 on 2019-06-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190611_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='meal',
            field=models.CharField(choices=[('B', 'Brimstone'), ('F', 'Fire'), ('T', 'Tacos'), ('C', 'Cotton Candy')], default='B', max_length=1),
        ),
    ]
