# Generated by Django 2.2 on 2019-06-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='soul',
            name='instruments',
            field=models.ManyToManyField(to='main_app.Instrument'),
        ),
    ]
